import = [
    "~/.config/alacritty/themes/themes/meliora.toml"
]

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Never"

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.normal]
family = "iosevkaterm nerd font mono"
style = "medium"

[scrolling]
history = 2000
