import = [
    "~/.config/alacritty/themes/themes/tomorrow_night_bright.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "mono"
#family = "fira code"
style = "medium"

[scrolling]
history = 2000

[window]
opacity = 0.9
dimensions = { columns = 130, lines = 35 }
dynamic_title = false
blur = true
