import = [
    "~/.config/alacritty/themes/themes/mellow.toml"
]

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Never"

[env]
TERM = "xterm-256color"

[font]
size = 8

[font.normal]
family = "fira code"
style = "regualar"

[scrolling]
history = 2000
