import = [
    "~/.config/alacritty/themes/themes/pastel_dark.toml"
]

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Never"

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.normal]
family = "Fira Code"
style = "Regular"

[scrolling]
history = 2000
